name: Renovate Generate

on:
  push:
    branches:
      - "renovate/**"

permissions:
  contents: write

jobs:
  generate:
    uses: openmcp-project/build/.github/workflows/renovate-generate.lib.yaml@292f9fc659aa7c9fa0ba004af43f161ad26ebb4c # main
    secrets: inherit
