name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@292f9fc659aa7c9fa0ba004af43f161ad26ebb4c # main
    secrets: inherit
