name: Validate Pull Request Content

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@9a76ad96274d299c5dc71fbecfd74b09d1bfef79 # main
    secrets: inherit